### PR TITLE
clean up confusing `origin()` and fix uncompressed reading

### LINKED ISSUE #87: Uncompressed Streamers cannot be read
https://github.com/tamasgal/UnROOT.jl/blob/ea2a6ba3244915fe336a13ec3d9ab8b0adb23c38/src/streamers.jl#L109

(on current master branch)
this line throws an `ERROR: Invalid class reference.` when reading a ROOT file that is not compressed at all (even the Streamers are not compressed).

If I print out all the `tag` > 0 from:
https://github.com/tamasgal/UnROOT.jl/blob/ea2a6ba3244915fe336a13ec3d9ab8b0adb23c38/src/streamers.jl#L198-L207

I see that, for a compressed file:
```julia
/home/akako/Downloads/Run2012BC_DoubleMuParked_Muons.root
tag = 0xffffffff
tag = 0xffffffff
tag = 0x8000011e
tag = 0xffffffff
tag = 0x8000011e
tag = 0x80002875
tag = 0x8000011e
tag = 0x80002875
tag = 0x8000011e
tag = 0x80002875
tag = 0x8000011e
tag = 0x800001dd
tag = 0x000001d9
tag = 0x00002871
tag = 0x00005ace
tag = 0x00008d26
tag = 0x0000bf80
tag = 0x0000f1e0
├─ Events
│  ├─ "nMuon"
│  ├─ "Muon_pt"
```

for a bugged uncomressed file:
```
┌ Debug: Unompressed stream at 58521775
└ @ UnROOT ~/.julia/dev/UnROOT/src/streamers.jl:98
┌ Debug: Found 19 streamers, continue with parsing.
└ @ UnROOT ~/.julia/dev/UnROOT/src/streamers.jl:107
tag = 0xffffffff
tag = 0xffffffff
tag = 0xffffffff
tag = 0xffffffff
tag = 0x8000013b
ERROR: Invalid class reference.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
```

### PR DESCRIPTION
**Pull request by Moelf**
fix #87

### CODE REVIEW

**Comment by aminnj** [comment]
If you revert all the `offset()` changes and insert this:
```diff
diff --git a/src/streamers.jl b/src/streamers.jl
index 1e80e76..4b14ffb 100644
--- a/src/streamers.jl
+++ b/src/streamers.jl
         tag = readtype(io, UInt32)
     end

+    if start < 0 && tkey.fClassName == "TTree"
+        start += tkey.fKeylen + tkey.fSeekKey
+        beg += tkey.fKeylen + tkey.fSeekKey
+    end
+
     if Int64(tag) & Const.kClassMask == 0
```
then `uncompressed.root`, `uncompressed2.root`, and the doublemu files will all work. Unit tests still pass too. It's just a bandaid, but maybe it works for now? If `start<0` is rare, then we actually don't do the string comparison with "TTree" and this TKey parsing is behind a LRU cache anyway.

**Comment by aminnj** [comment]
Now, a comparison. uncompressed file [here](http://uaf-1.t2.ucsd.edu/~namin/dump/uncompressed_Run2012BC_DoubleMuParked_Muons.root). Both warm/repeated several times.

### julia
```julia
julia> using UnROOT

julia> const t = LazyTree(ROOTFile("uncompressed_Run2012BC_DoubleMuParked_Muons.root"),"Events");

julia> @time let nmu=0
           for evt in t
               nmu += length(evt.Muon_pt)
           end
           nmu
       end
```
```julia
  2.736618 seconds (15.79 k allocations: 2.816 GiB, 8.12% gc time)
149322456
```
### C++ (TTreeReader)
```cpp
#include "TFile.h"
#include "TH1F.h"
#include "TTreeReader.h"
#include "TStopwatch.h"
 
void simple() {
   TFile *f = TFile::Open("uncompressed_Run2012BC_DoubleMuParked_Muons.root");
   TTreeReader reader("Events", f);
   TTreeReaderArray<float> Muon_pt(reader, "Muon_pt");
   TStopwatch timer; timer.Start();
   int nmu = 0;
   while (reader.Next()) {
       nmu += Muon_pt.GetSize();
   }
   timer.Stop(); timer.Print();
   std::cout << nmu << std::endl;
}

```
```bash
# interpreted
$ root -b -q -n simple.C
Real time 0:00:03, CP time 3.230
149322456

# compiled
$ root -b -q -n simple.C+
Real time 0:00:02, CP time 2.400
149322456
```

In terms of speed, julia is in between the interpreted and compiled `TTreeReader` approach. ROOT's zlib implementation is pretty good apparently.

|              | julia (s)    | ROOT interpreted (s) | ROOT compiled (s) |
|--------------|----------|------------------|---------------|
| uncompressed | 2.737 | 3.230            | 2.400         |
| zlib         | 7.645 | 3.590            | 2.740         |

**Comment by aminnj** [comment]
For future reference, the julia time can be improved by 10% with
```diff
diff --git a/src/iteration.jl b/src/iteration.jl
index 51f0901..12d0b6b 100644
--- a/src/iteration.jl
+++ b/src/iteration.jl
@@ -158,7 +158,7 @@ function Base.getindex(ba::LazyBranch{T,J,B}, idx::Integer) where {T,J,B}
         ba.buffer_range[tid] = br
     end
     localidx = idx - br.start + 1
-    return ba.buffer[tid][localidx]
+    return @inbounds ba.buffer[tid][localidx]
 end

 function Base.iterate(ba::LazyBranch{T,J,B}, idx=1) where {T,J,B}
diff --git a/src/root.jl b/src/root.jl
index 8f9df77..69ad495 100644
--- a/src/root.jl
+++ b/src/root.jl
@@ -247,7 +247,7 @@ function interped_data(rawdata, rawoffsets, ::Type{T}, ::Type{J}) where {T, J<:J
             end
         end
         resize!(rawdata, dp)
-        real_data = map(ntoh, reinterpret(T, rawdata))
+        real_data = ntoh.(reinterpret(T, rawdata))
         offset .÷= _size
         offset .+= 1
         VectorOfVectors(real_data, offset)
```

**Comment by Moelf** [comment]
I think what you have is fine. I tested a few things to speed up zlib decompression and didn't work. I suspect it may be because ROOT has pre-fetch decompression or similar. Since we know the slow down is after:
https://github.com/tamasgal/UnROOT.jl/blob/04a4487ce1f8bfc06a81511c2dd00f0f57cfbac6/src/types.jl#L123-L126

**Comment by Moelf** [comment]
fixed in #89

**Pull request closed without merging**
