### PR TITLE
fix Vector{Bool} branches and factorize `interped_data`

### PR DESCRIPTION
**Pull request by aminnj**
The change in https://github.com/tamasgal/UnROOT.jl/pull/93 results in `BitVector` instead of `Vector{Bool}` which breaks LazyBranch. We didn't have a test for it, but I added one here. I split up the large `interped_data` into smaller chunks for non-, singly-, doubly-jagged branches so that it's easier to specialize on Bool. Evidently this breaks some LV64 test cases which I'm still figuring out.

```julia
TLorentzVector: Error During Test at /Users/namin/.julia/dev/UnROOT/test/runtests.jl:238
  Test threw exception
  Expression: (branch[1]).x == 1.0
  MethodError: interped_data(::Vector{UInt8}, ::Vector{Int32}, ::Type{LorentzVector{Float64}}, ::Type{UnROOT.Nojagg}) is ambiguous. Candidates:
    interped_data(rawdata, rawoffsets, ::Type{T}, ::Type{UnROOT.Nojagg}) where T in UnROOT at /Users/namin/.julia/dev/UnROOT/src/root.jl:196
    interped_data(rawdata, rawoffsets, ::Type{LorentzVector{Float64}}, ::Type{J}) where {T, J<:UnROOT.JaggType} in UnROOT at /Users/namin/.julia/dev/UnROOT/src/custom.jl:76
  Possible fix, define
    interped_data(::Any, ::Any, ::Type{LorentzVector{Float64}}, ::Type{UnROOT.Nojagg})
  Stacktrace:
   [1] basketarray(f::ROOTFile, branch::UnROOT.TBranchElement_10, ithbasket::Int64)
     @ UnROOT ~/.julia/dev/UnROOT/src/iteration.jl:57
```

### CODE REVIEW

**Comment by aminnj** [comment]
Alternatively, I could just undo the factorization of `interpred_data` and simply add
```julia
function interped_data(rawdata, rawoffsets, ::Type{T}, ::Type{Nojagg}) where {T<:Bool}
    return map(ntoh,reinterpret(T, rawdata))
end
```
but then it's less nice to read the long if-else chain.

**Comment by aminnj** [comment]
Since the typing in `root.jl` isn't a catch-all, I restricted the typing of various things in `custom.jl`. Unit tests pass, but @Moelf @tamasgal can you make sure I didn't do anything destructive? If it's easier, I'll just do what I wrote in my previous message.

**Comment by Moelf** [comment]
Tamas probably uses more `custom.jl` than I do, maybe he will have some input as an expert user.

**Comment by tamasgal** [comment]
I am back on track. Thanks for this PR, I will check it and report back, but I think it should be fine since the test coverage is pretty good for custom stuff. That's why I wanted to leave it there in first place ;)

**Comment by tamasgal** [comment]
I tried it but I get ambiguities. I probably need to change the way I deal with `interped_data()`:

```
MethodError: interped_data(::Vector{UInt8}, ::Vector{Int32}, ::Type{NeRCA.KM3NETDAQEventHeader}, ::Type{UnROOT.Nojagg}) is ambiguous. Candidates:
  interped_data(rawdata, rawoffsets, ::Type{T}, ::Type{UnROOT.Nojagg}) where T in UnROOT at /home/tgal/Dev/UnROOT.jl/src/root.jl:196
  interped_data(rawdata, rawoffsets, ::Type{NeRCA.KM3NETDAQEventHeader}, ::Type{J}) where {T, J<:UnROOT.JaggType} in NeRCA at /home/tgal/Dev/NeRCA.jl/src/io/root.jl:67
Possible fix, define
  interped_data(::Any, ::Any, ::Type{NeRCA.KM3NETDAQEventHeader}, ::Type{UnROOT.Nojagg})

Stacktrace:
  [1] basketarray(f::ROOTFile, branch::UnROOT.TBranchElement_10, ithbasket::Int64)
    @ UnROOT ~/Dev/UnROOT.jl/src/iteration.jl:57
  [2] getindex(ba::LazyBranch{NeRCA.KM3NETDAQEventHeader, UnROOT.Nojagg, Vector{NeRCA.KM3NETDAQEventHeader}}, idx::Int64)
    @ UnROOT ~/Dev/UnROOT.jl/src/iteration.jl:152
  [3] iterate
    @ ~/Dev/UnROOT.jl/src/iteration.jl:166 [inlined]
  [4] iterate
    @ ~/Dev/UnROOT.jl/src/iteration.jl:165 [inlined]
  [5] copyto_unaliased!(deststyle::IndexLinear, dest::Vector{NeRCA.KM3NETDAQEventHeader}, srcstyle::IndexCartesian, src::LazyBranch{NeRCA.KM3NETDAQEventHeader, UnROOT.Nojagg, Vector{NeRCA.KM3NETDAQEventHeader}})
    @ Base ./abstractarray.jl:975
  [6] copyto!
    @ ./abstractarray.jl:950 [inlined]
  [7] copyto_axcheck!
    @ ./abstractarray.jl:1056 [inlined]
  [8] Array
    @ ./array.jl:540 [inlined]
  [9] convert(#unused#::Type{Vector{NeRCA.KM3NETDAQEventHeader}}, a::LazyBranch{NeRCA.KM3NETDAQEventHeader, UnROOT.Nojagg, Vector{NeRCA.KM3NETDAQEventHeader}})
    @ Base ./array.jl:532
 [10] OnlineFile(filename::String)
    @ NeRCA ~/Dev/NeRCA.jl/src/io/root.jl:91
 [11] reco(fname::String, calib::Calibration, sparams::SingleDURecoParams, outfile::String; n_events::Int64)
    @ Main ./In[5]:6
 [12] top-level scope
    @ ./In[6]:19
 [13] eval
    @ ./boot.jl:360 [inlined]
 [14] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1094
```

**Comment by tamasgal** [comment]
Ah wait, I am dumb. This is colliding with an existing implementation in the core library...

**Comment by tamasgal** [comment]
OK, I refactored `custom.jl` a little bit and added more tests for full coverage. Can you rebase onto `master`?

**Comment by aminnj** [comment]
I screwed up the merge, so I replaced this PR with https://github.com/tamasgal/UnROOT.jl/pull/106 . ;)

**Pull request closed without merging**
