### PR TITLE
Interpret doubly jagged branches

### PR DESCRIPTION
**Pull request by aminnj**
Probably closes https://github.com/tamasgal/UnROOT.jl/issues/58 . Surprisingly, it's not very many lines to allow UnROOT to interpret doubly jagged (jagged of jagged) branches. Now one can do

```julia
julia> f = ROOTFile("/Users/namin/.julia/dev/UnROOT/test/samples/tree_with_doubly_jagged.root");
julia> f["t1/bi"]
5-element Vector{Vector{Vector{Int32}}}:
 [[2], [3, 5]]
 [[7, 9, 11], [13]]
 [[17], [19], []]
 []
 [[]]

julia> LazyTree(f, "t1")
 Row │ bi                               bf
     │ Vector{Vector{I                  Vector{Vector{F
─────┼────────────────────────────────────────────────────────────────────────────
 1   │ Vector{Int32}[[2], [3, 5]]       Vector{Float32}[[2.5], [3.5, 5.5]]
 2   │ Vector{Int32}[[7, 9, 11], [13]]  Vector{Float32}[[7.5, 9.5, 11.5], [13.5]]
 3   │ Vector{Int32}[[17], [19], []]    Vector{Float32}[[17.5], [19.5], []]
 4   │ Vector{Int32}[]                  Vector{Float32}[]
 5   │ Vector{Int32}[[]]                Vector{Float32}[[]]
```

Sorry, yes, 9 is not prime :(

### CODE REVIEW

**Comment by tamasgal** [comment]
`Offsetjaggjagg`? 😅

**Review by tamasgal — APPROVED** [review]

**Comment by Moelf** [comment]
I'm late to the party. What's the general recursive nature of this pattern? It's definitely very different between nojagg - singly jagged - doubly jagged. But maybe n-th jagged is just recursively doing doubly jagged?

Not saying I want to support them, just curious

**Comment by aminnj** [comment]
Variable names are hard. I'd support changing `Offsetjaggjagg` to something that sounds a little less...weird :)

I made a branch with a triply jagged row `[[[102], [103,105]], [[107,109,111], [113]]]`. It fails of course, but the structure is like this

```julia
julia> ntoh.(reinterpret(Int32, data[offsets[1]+1+10:offsets[2]]))
13-element Vector{Int32}:
   2
   1
 102
   2
 103
 105
   2
   3
 107
 109
 111
   1
 113
```

If I try to parse it as a doubly jagged array, it fails. I thought I would be able to do that and see the structure of the innermost array within it, but apparently not. So it's not so trivial to do triply jagged.

**Comment by aminnj** [comment]
FWIW, I've never ever seen a triply jagged branch in the wild.

**Comment by aminnj** [comment]
Ah nevermind, thinking about the triply jagged thing again. One row: `[[[102], [103,105]], [[107,109,111], [113]]]`. "Raw" interpretation:
```julia
julia> ntoh.(reinterpret(Int32, data[offsets[1]+1+10:offsets[2]]))
13-element Vector{Int32}:
   2
   1
 102
   2
 103
 105
   2
   3
 107
 109
 111
   1
 113
```

It makes sense when adding some spaces:
```julia
   2          # 2 upcoming sub arrays
       1      # 1 upcoming sub-sub array
         102
       2
         103
         105
   2
       3
         107
         109
         111
       1
         113
```

**Comment by tamasgal** [comment]
Yes, that's indeed what I just wanted to point out `;)`

I think we can think about implementing it once it's needed. I also have not seen triply jagged arrays yet and in KM3NeT we have some pretty wild structures `:)`

**Pull request merged**
